import { useEffect,useMemo,useRef,useState,type KeyboardEvent } from 'react';
import { activityLabels,activityTypes,type ActivityPage,type ActivityQuery,type ActivityEvidence } from '../../packages/contracts/activity.js';
import { sourceLabel } from '../../packages/contracts/archive.js';
import { beijingDate } from '../../packages/contracts/reports.js';
import { addDays } from '../../packages/contracts/work-views.js';
import './activity.css';

type Request=(path:string,signal?:AbortSignal,method?:'POST',body?:unknown)=>Promise<Response>;
const params=(value:object)=>new URLSearchParams(Object.entries(value).filter(([,item])=>item!==undefined).map(([key,item])=>[key,String(item)]));
const time=(value:string|null)=>value?new Date(value).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'}):'时间未知';
const link=(evidence:ActivityEvidence)=>evidence.conversationPath??evidence.webPath;
function fromHash(hash:string):ActivityQuery{const q=new URLSearchParams(hash.split('?')[1]);return {date:q.get('date')??beijingDate(new Date()),employeeId:q.get('employeeId')??undefined,source:q.get('source') as ActivityQuery['source']||undefined,project:q.get('project')??undefined,type:q.get('type') as ActivityQuery['type']||undefined,version:q.get('version')??undefined,offset:Number(q.get('offset')??0)};}
function Rhythm({page}:{page:ActivityPage}){
  const [table,setTable]=useState(false),[tooltip,setTooltip]=useState('');
  const chart=useRef<HTMLDivElement>(null),[width,setWidth]=useState(800),[now,setNow]=useState(()=>new Date());
  useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(!chart.current)return;const observer=new ResizeObserver(entries=>setWidth(Math.max(180,entries[0]!.contentRect.width)));observer.observe(chart.current);return()=>observer.disconnect();},[table]);
  const left=width<400?58:76,plot=width-left-20,start=Date.parse(page.scope.date+'T00:00:00+08:00'),px=(value:string)=>left+Math.max(0,Math.min(1,(Date.parse(value)-start)/86400000))*plot;
  const height=page.lanes.length*48+40,nowX=beijingDate(now)===page.scope.date?px(now.toISOString()):null;
  const focus=(label:string)=>({onFocus:()=>setTooltip(label),onMouseEnter:()=>setTooltip(label),onBlur:()=>setTooltip(''),onMouseLeave:()=>setTooltip(''),onKeyDown:(event:KeyboardEvent)=>{if(event.key==='Escape')setTooltip('');}});
  return <section className="activity-rhythm" aria-label="对话节奏"><div className="activity-section-head"><h2>对话节奏</h2><div className="activity-view-switch" role="group" aria-label="节奏视图"><button aria-pressed={!table} onClick={()=>setTable(false)}>节奏图表</button><button aria-pressed={table} onClick={()=>setTable(true)}>节奏表格</button></div></div>
    <div className="activity-legend"><span data-agent="codex-cli">Codex CLI</span><span data-agent="codex-desktop">Codex Desktop</span><span data-agent="claude-code-cli">Claude Code</span><span className="legend-dot">提问</span><span className="legend-rework">返工</span><span className="legend-wait">长等待</span></div>
    {table?<div className="activity-table-wrap"><table className="activity-lane-table" aria-label="对话节奏表格"><thead><tr><th>员工</th><th>类型</th><th>时间</th><th>来源</th></tr></thead><tbody>{page.lanes.flatMap(lane=>[
      ...lane.sessions.map(session=><tr key={session.id}><th>{lane.employee}</th><td>会话记录区间<span className="activity-secondary">{sourceLabel(session.source)} · {session.state==='in-progress'?'进行中':session.state==='waiting-input'?'等待输入':session.state==='interrupted'?'已中断':'状态未知'}</span></td><td>{time(session.observedFrom)} — {time(session.observedTo)}</td><td><a href={link(session.evidence)}>查看来源</a></td></tr>),
      ...lane.points.map(point=><tr key={point.id}><th>{lane.employee}</th><td>{activityLabels[point.type]}</td><td>{time(point.timestamp)}</td><td><a href={link(point.evidence)}>查看原句</a></td></tr>),
      ...lane.segments.map(segment=><tr key={segment.id}><th>{lane.employee}</th><td>长等待</td><td>{time(segment.startedAt)} — {time(segment.endedAt)}<span className="activity-secondary">当日 {Math.round(segment.durationInScopeMs/60000*10)/10} 分钟</span></td><td><a href={link(segment.evidence)}>查看用户回复</a></td></tr>),
    ])}</tbody></table></div>:<div className="activity-chart" ref={chart}><svg viewBox={`0 0 ${width} ${Math.max(88,height)}`} role="img" aria-label="对话节奏">
      {(width<400?[0,6,12,18,24]:[0,4,8,12,16,20,24]).map(hour=><g key={hour}><line className="activity-grid" x1={left+hour/24*plot} x2={left+hour/24*plot} y1="0" y2={height-25}/><text className="activity-axis" x={left+hour/24*plot} y={height-6} textAnchor="middle">{String(hour).padStart(2,'0')}</text></g>)}
      {nowX!==null&&<g><line className="activity-now" x1={nowX} x2={nowX} y1="0" y2={height-25}/><title>现在 {time(now.toISOString())}</title></g>}
      {page.lanes.map((lane,index)=>{const y=index*48+24;return <g key={lane.employeeId}><text className="activity-person" x={left-10} y={y+4} textAnchor="end">{lane.employee}</text>
        {lane.sessions.map(session=>{const label=`${lane.employee} · ${sourceLabel(session.source)} · ${time(session.observedFrom)} — ${time(session.observedTo)}`;return <a key={session.id} href={link(session.evidence)} aria-label={label} {...focus(label)}><rect className="activity-session" data-agent={session.source} x={px(session.observedFrom)} y={y-7} width={Math.max(4,px(session.observedTo)-px(session.observedFrom))} height="14" rx="5"/></a>;})}
        {lane.segments.map(segment=>{const label=`${lane.employee} · 长等待 · ${time(segment.startedAt)} — ${time(segment.endedAt)}`;return <a key={segment.id} href={link(segment.evidence)} aria-label={label} {...focus(label)}><rect className="activity-wait" x={px(segment.startedAt)} y={y-7} width={Math.max(3,px(segment.endedAt)-px(segment.startedAt))} height="14"/></a>;})}
        {lane.points.map(point=>{const label=`${lane.employee} · ${activityLabels[point.type]} · ${time(point.timestamp)}`;return <a key={point.id} href={link(point.evidence)} aria-label={label} {...focus(label)}><circle className="activity-point-hit" cx={px(point.timestamp!)} cy={y} r="10"/><circle className="activity-point" data-rework={point.type==='rework'||undefined} cx={px(point.timestamp!)} cy={y} r="4"/></a>;})}
      </g>;})}
    </svg>{tooltip&&<div role="tooltip" className="activity-tooltip">{tooltip}</div>}</div>}
    {!page.lanes.length&&<p className="activity-empty">暂无对话节奏</p>}
  </section>;
}
export function ActivityRecords({request,hash}:{request:Request;hash:string}){
  const query=useMemo(()=>fromHash(hash),[hash]);
  const [page,setPage]=useState<ActivityPage>(),[facets,setFacets]=useState<ActivityPage['lanes']>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0),[project,setProject]=useState(query.project??'');
  useEffect(()=>{setProject(query.project??'');},[query]);
  useEffect(()=>{const abort=new AbortController();setBusy(true);setError('');setPage(undefined);request('/api/activity?'+params(query),abort.signal).then(response=>response.json()).then(async(result:ActivityPage)=>{
      const lanes=new Map(result.lanes.map(lane=>[lane.employeeId,lane]));let offset=result.nextLaneOffset;
      while(offset!==null&&!abort.signal.aborted){const next:ActivityPage=await(await request('/api/activity?'+params({...query,version:result.version,section:'lanes',offset}),abort.signal)).json();
        for(const lane of next.lanes){const existing=lanes.get(lane.employeeId);if(existing){existing.sessions.push(...lane.sessions);existing.points.push(...lane.points);existing.segments.push(...lane.segments);}else lanes.set(lane.employeeId,lane);}offset=next.nextOffset;}
      if(abort.signal.aborted)return;setPage({...result,lanes:[...lanes.values()]});setFacets(previous=>[...new Map([...previous,...result.employeeOrder.map(employee=>({...employee,sessions:[],points:[],segments:[]}))].map(lane=>[lane.employeeId,lane])).values()]);}).catch(error=>{if(!abort.signal.aborted)setError(error.message);}).finally(()=>{if(!abort.signal.aborted)setBusy(false);});return()=>abort.abort();},[query,retry]);
  const navigate=(next:Partial<ActivityQuery>,keep=false)=>{const value={...fromHash(location.hash),...next,...(!keep?{version:undefined,offset:0}:{})};const target='#activity?'+params(value);if(location.hash===target){if(hash===target)setRetry(value=>value+1);}else location.hash=target;};
  async function download(){if(!page)return;try{const response=await request('/api/activity/export?'+params({...query,version:page.version,offset:0}));const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=`skynet-activity-${page.scope.date}-${page.version}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){setError((error as Error).message);}}
  return <section className="activity-records workspace-page" aria-label="活动记录" aria-busy={busy}>
    <div className="activity-page-head"><div><div className="activity-eyebrow">观察</div><h1>活动记录</h1></div><div className="activity-actions"><button disabled={busy} onClick={()=>navigate({})}>刷新</button><button disabled={!page||busy} onClick={download}>导出当前版本</button></div></div>
    <form className="activity-filters" onSubmit={event=>{event.preventDefault();navigate({project:project||undefined});}}><div className="activity-date-controls"><button type="button" aria-label="前一天" onClick={()=>navigate({date:addDays(query.date!,-1)})}>‹</button><input type="date" aria-label="活动日期" value={query.date??''} onChange={event=>{if(event.target.value)navigate({date:event.target.value});}}/><button type="button" aria-label="后一天" onClick={()=>navigate({date:addDays(query.date!,1)})}>›</button></div>
      <label><span>员工</span><select aria-label="活动员工" value={query.employeeId??''} onChange={event=>navigate({employeeId:event.target.value||undefined})}><option value="">全部员工</option>{facets.toSorted((a,b)=>a.employee.localeCompare(b.employee,'zh-CN')).map(lane=><option key={lane.employeeId} value={lane.employeeId}>{lane.employee}</option>)}</select></label>
      <label><span>Agent</span><select aria-label="活动 Agent" value={query.source??''} onChange={event=>navigate({source:event.target.value as ActivityQuery['source']||undefined})}><option value="">全部 Agent</option>{(['codex-cli','codex-desktop','claude-code-cli'] as const).map(source=><option key={source} value={source}>{sourceLabel(source)}</option>)}</select></label>
      <label className="activity-project"><span>项目</span><input value={project} aria-label="活动项目" placeholder="全部项目" maxLength={1024} onChange={event=>setProject(event.target.value)}/></label>
      <label><span>事件</span><select aria-label="活动类型" value={query.type??''} onChange={event=>navigate({type:event.target.value as ActivityQuery['type']||undefined})}><option value="">全部事件</option>{activityTypes.map(type=><option key={type} value={type}>{activityLabels[type]}</option>)}</select></label><button type="submit">应用</button>
    </form><div className="workspace-scroll activity-scroll">
      {busy&&<p role="status">正在读取活动…</p>}{error&&<div role="alert"><p>{error}</p><button onClick={()=>setRetry(value=>value+1)}>重试</button></div>}
      {page&&<><div className="activity-scope"><span>{page.scope.date} · 北京时间</span><span>{page.total} 条 · v{page.revision}{page.dataAsOf&&' · 截至 '+new Date(page.dataAsOf).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}</span></div><Rhythm page={page}/>
        <section className="activity-list"><div className="activity-section-head"><h2>对话事件</h2><span>{page.total} 条</span></div><table aria-label="活动记录"><thead><tr><th>时间</th><th>员工 / 会话</th><th>事件 / 原句</th></tr></thead><tbody>{page.events.map(event=><tr key={event.id} data-kind={event.type}>
          <td className="activity-time"><time dateTime={event.timestamp??undefined}>{time(event.timestamp)}</time>{event.sourceDate&&event.sourceDate!==page.scope.date&&<span className="activity-secondary">{event.sourceDate}</span>}</td>
          <td className="activity-owner"><strong>{event.employee}</strong><span className="activity-secondary">{sourceLabel(event.source)}</span><span className="activity-project-name" title={event.project}>{event.project||'未归类项目'}</span><a className="activity-session-id" href={'#'+event.snapshotId}>会话 {event.sessionId.slice(0,8)}</a></td>
          <td className="activity-body"><div className="activity-event-label"><span>{activityLabels[event.type]}</span>{event.backfill==='observed'&&<span className="activity-badge">补传</span>}{event.basis==='inferred'&&<span className="activity-badge">模型推断</span>}</div><a className="activity-excerpt" href={link(event.evidence)}>{['session-start','compaction'].includes(event.type)?'查看原始记录':event.excerpt}</a>{event.durationMs!==undefined&&<span className="activity-secondary">{Math.round(event.durationMs/60000*10)/10} 分钟{event.parallel==='observed'?' · 期间在其他会话中活动':''}</span>}{event.delivery&&<details><summary>投递记录</summary><span className="activity-secondary">连接中断 {event.delivery.disconnectedAttempts} 次 · 首次 {time(event.delivery.firstDisconnectedAt)}</span><span className="activity-secondary">采集端确认 {time(event.delivery.acknowledgedAt)} · 记录 {event.delivery.revision.slice(0,12)}</span></details>}{event.inference&&<details><summary>分析依据</summary><a href={event.inference.webPath}>{event.inference.quote}</a><span className="activity-secondary">分析 {event.analysisVersion} · 版本 {event.inference.version.slice(0,12)}</span></details>}</td>
        </tr>)}</tbody></table>{page.total===0&&<p className="activity-empty">暂无活动记录</p>}
          {page.total>25&&<div className="activity-pagination"><button disabled={busy||query.offset===0} onClick={()=>navigate({version:page.version,offset:Math.max(0,query.offset-25)},true)}>上一页活动</button><span>{Math.floor(query.offset/25)+1} / {Math.ceil(page.total/25)}</span><button disabled={busy||page.nextOffset===null} onClick={()=>navigate({version:page.version,offset:page.nextOffset!},true)}>下一页活动</button></div>}
        </section><details className="activity-coverage"><summary>来源与版本</summary><dl><dt>来源时间待定</dt><dd>{page.coverage.unknownTime}</dd><dt>权限等待</dt><dd>未知</dd><dt>会话结束边界</dt><dd>未知</dd><dt>版本</dt><dd>{page.version}</dd></dl></details>
      </>}
    </div>
  </section>;
}
