import type { CapabilityProfilePage,profileSections } from '../../packages/contracts/capability-profile.js';
import { sourceLabel } from '../../packages/contracts/archive.js';
import { activityLabels } from '../../packages/contracts/activity.js';
import { analysisLabels,assessmentLabels } from '../../packages/contracts/analysis.js';
import { taskTypeLabels } from '../../packages/contracts/session-insights.js';
import { withProfileSourceReturn } from './profile-source-navigation.js';

type Props={profile:CapabilityProfilePage;more:(section:typeof profileSections[number])=>void;busy:boolean};
const num=(value:number|null|undefined)=>value==null?'未知':value.toLocaleString('zh-CN',{maximumFractionDigits:1});
const states={'not-scheduled':'尚未生成',queued:'已入队','waiting-analysis':'等待分析',ready:'已生成',partial:'材料或分析不完整',unavailable:'暂无可用主题'};
export function ProfileWork({profile,more,busy}:Props){
  const groups=new Map<string,CapabilityProfilePage['work']['items']>();
  for(const row of profile.work.items){if(row.item.category==='blocker')continue;const key=JSON.stringify([row.item.project,row.item.theme]);groups.set(key,[...groups.get(key)??[],row]);}
  const blockers=profile.work.items.filter(row=>row.item.category==='blocker');
  function finding(row:CapabilityProfilePage['work']['items'][number]){return <article key={row.id} className="profile-work-item"><header><span>{analysisLabels[row.item.category]} · {assessmentLabels[row.item.assessment]}</span><time>{row.date}</time></header><p>{row.item.text}</p>{row.item.citations.length>0&&<details><summary>原文 · {row.item.citations.length}</summary>{row.item.citations.map((citation,index)=><div className="profile-work-citation" key={index}><q>{citation.quote}</q><a href={citation.webPath}>原文 {index+1}</a></div>)}</details>}</article>;}
  return <section id="profile-work" tabIndex={-1} className="profile-section" aria-label="工作内容"><h2>工作内容</h2>{[...groups].map(([key,items])=><section className="profile-work-theme" key={key}><header><h3>{items[0]!.item.theme||'未归类主题'}</h3><span>{items[0]!.item.project||'未归类项目'}</span></header>{items.map(finding)}</section>)}{!!blockers.length&&<section className="profile-blockers" aria-label="记录到的阻塞"><h3>记录到的阻塞</h3>{blockers.map(finding)}</section>}
    {!profile.work.items.length&&<p className="profile-empty">暂无工作内容</p>}{profile.pages.work.nextOffset!==null&&<button disabled={busy} onClick={()=>more('work')}>更多工作事项</button>}
    <details className="profile-report-sources" open><summary>日报与周报 · {profile.pages.reports.total}</summary><ul>{profile.work.reports.map(report=><li key={report.id}>{report.version?<a href={withProfileSourceReturn(report.path,location.hash)} aria-label={(report.kind==='daily'?'日报 ':'周报 ')+report.from}>{report.kind==='daily'?'日报':'周报'} {report.from}{report.kind==='weekly'?' — '+report.to:''}</a>:<span>{report.kind==='daily'?'日报':'周报'} {report.from}</span>}<small>{states[report.state]}{report.refreshPending?' · 有更新待处理':''}</small></li>)}</ul>{profile.pages.reports.nextOffset!==null&&<button disabled={busy} onClick={()=>more('reports')}>更多来源报告</button>}</details>
  </section>;
}
export function ProfileSessions({profile,more,busy}:Props){return <section id="profile-sessions" tabIndex={-1} className="profile-section" aria-label="会话"><header className="profile-section-heading"><h2>会话 <small>{profile.pages.sessions.total}</small></h2><a href={profile.references.efficiency.path}>会话产效报表</a></header><div className="profile-table"><table aria-label="画像会话"><thead><tr><th>会话</th><th>来源日期</th><th>Token 输入</th><th>提示词</th><th>已验证</th><th>产效比</th><th>返工</th><th>等待占比</th></tr></thead><tbody>{profile.sessions.map(row=><tr key={row.sessionId}><th><a href={row.webPath}>{row.sourceSessionId}</a><small>{sourceLabel(row.source)} · {taskTypeLabels[row.taskType]} · 模型推断</small><small>{row.projects.map(project=>project||'未归类项目').join(' · ')}</small></th><td>{row.dates.join('、')||'未知'}</td><td>{num(row.tokens)}{row.tokens===null&&row.knownTokens>0&&<small>已知 {num(row.knownTokens)}</small>}</td><td>{row.userTurns}</td><td>{num(row.verified)}</td><td>{num(row.efficiency.value)}<small>{num(row.efficiency.numerator)} / {num(row.efficiency.denominator)} Token</small></td><td>{num(row.rework)}</td><td>{row.waitFraction?.value==null?'未知':num(row.waitFraction.value*100)+'%'}{row.waitFraction?.value!=null&&<small>{num(row.waitFraction.numerator)} / {num(row.waitFraction.denominator)} ms</small>}</td></tr>)}</tbody></table></div>{!profile.sessions.length&&<p className="profile-empty">暂无会话</p>}{profile.pages.sessions.nextOffset!==null&&<button disabled={busy} onClick={()=>more('sessions')}>更多会话</button>}<details className="profile-formula"><summary>会话指标口径</summary><p>已验证结果、任务类型与返工为模型推断。产效比是已验证结果 / Token 输入 × 1,000,000，只在同类任务内参考；等待占比为已知等待 / 已知活动区间。未知值不补零。</p></details></section>;}
export function ProfileActivity({profile,more,busy}:Props){return <section id="profile-activity" tabIndex={-1} className="profile-section" aria-label="最近活动"><h2>最近活动</h2><nav className="profile-activity-links" aria-label="完整活动来源">{profile.recentActivity.references.map(reference=><a key={reference.version} href={reference.path}>查看 {reference.date} 的活动</a>)}</nav>{profile.recentActivity.events.length?<ol className="profile-activity-feed">{profile.recentActivity.events.map(event=><li key={event.id}><time>{event.timestamp?new Date(event.timestamp).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'来源时间未知'}</time><div><header><strong>{activityLabels[event.type]}</strong>{event.basis==='inferred'&&<small>模型推断</small>}<span>{sourceLabel(event.source)}</span></header>{event.excerpt&&<p>{event.excerpt}</p>}<a href={event.evidence.conversationPath??event.evidence.webPath}>查看原文</a></div></li>)}</ol>:<p className="profile-empty">暂无活动</p>}{profile.pages.activity.nextOffset!==null&&<button disabled={busy} onClick={()=>more('activity')}>更多画像活动</button>}</section>;}
