import {useEffect,useLayoutEffect,useRef,useState,type ReactNode,type CSSProperties} from 'react';
import type {PromptReport,PromptReportQuery,PromptFraction,PromptExample} from '../../packages/contracts/prompt-report.js';
import {promptElementLabels,type InsightCitation} from '../../packages/contracts/session-insights.js';
import {sourceLabel} from '../../packages/contracts/archive.js';
import './usage-metrics.css';
import './prompt-report.css';
type Request=(path:string,signal?:AbortSignal,method?:'POST',body?:unknown)=>Promise<Response>;
const params=(q:object)=>new URLSearchParams(Object.entries(q).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)]));
function hashQuery():PromptReportQuery{const values=new URLSearchParams(location.hash.split('?')[1]);return {period:(values.get('period')??'this-week') as PromptReportQuery['period'],...Object.fromEntries(['employeeId','source','project','version','usageVersion','week'].flatMap(key=>values.has(key)?[[key,values.get(key)!]]:[]))};}
const pct=(value:number|null)=>value===null?'—':new Intl.NumberFormat('zh-CN',{style:'percent',maximumFractionDigits:1}).format(value);
const count=(f:PromptFraction)=>`${f.numerator} / ${f.denominator}${f.unknown?` · ${f.unknown} 未知`:''}`;
const groups=[{label:'实现与修复',types:['implementation','fix']},{label:'排查',types:['investigation']},{label:'重构与测试',types:['refactor','test']},{label:'运维与整理',types:['operations','documentation']},{label:'未知',types:['unknown']}];
function Figure({label,title,children,table,note}:{label:string;title:string;children:ReactNode;table:ReactNode;note?:ReactNode}){const [chart,setChart]=useState(true);return <section className="usage-figure prompt-figure" aria-label={label}><div className="usage-figure-head"><h2>{title}</h2><div className="usage-view-toggle"><button aria-label={`${label}切换为图表`} aria-pressed={chart} onClick={()=>setChart(true)}>图表</button><button aria-label={`${label}切换为表格`} aria-pressed={!chart} onClick={()=>setChart(false)}>表格</button></div></div>{chart?children:<div className="prompt-table-wrap">{table}</div>}{note&&<p className="prompt-note">{note}</p>}</section>;}
function usePromptTooltip(active:string){
  const root=useRef<HTMLDivElement>(null),tip=useRef<HTMLParagraphElement>(null);
  useLayoutEffect(()=>{
    if(!active)return;
    const position=()=>{
      const box=root.current,popup=tip.current,anchor=box?.querySelector<HTMLElement>('[aria-expanded="true"]');if(!box||!popup||!anchor)return;
      const base=box.getBoundingClientRect(),target=anchor.getBoundingClientRect();let top=0,bottom=innerHeight;
      for(let parent=box.parentElement;parent;parent=parent.parentElement){const css=getComputedStyle(parent);if(/auto|scroll|hidden|clip/.test(css.overflowY)){const rect=parent.getBoundingClientRect();top=Math.max(top,rect.top+parent.clientTop);bottom=Math.min(bottom,rect.top+parent.clientTop+parent.clientHeight);}}
      const above=Math.max(0,target.top-top-6),below=Math.max(0,bottom-target.bottom-6),up=above>below,room=Math.max(above,below);
      popup.style.maxHeight=Math.min(180,room)+'px';const height=popup.getBoundingClientRect().height;
      popup.style.top=((up?target.top-height-4:target.bottom+4)-base.top)+'px';
    };
    position();window.addEventListener('resize',position);window.addEventListener('scroll',position,true);
    return()=>{window.removeEventListener('resize',position);window.removeEventListener('scroll',position,true);};
  },[active]);
  return {root,tip};
}
function Bars({rows,percent=false}:{rows:{label:string;value:number|null;detail:string}[];percent?:boolean}){
  const [active,setActive]=useState(''),clicked=useRef(''),max=percent?1:Math.max(1,...rows.map(row=>row.value??0));
  const close=()=>{clicked.current='';setActive('');},tooltip=rows.find(row=>row.label===active)?.detail,{root,tip}=usePromptTooltip(active);
  return <div ref={root} className="prompt-bars" onPointerLeave={event=>{if(event.pointerType==='mouse')close();}} onKeyDown={event=>{if(event.key==='Escape')close();}}>{rows.map(row=><div className="prompt-bar-row" key={row.label}><span>{row.label}</span><button aria-label={`${row.label}：${percent?pct(row.value):row.value??'未知'}，${row.detail}`} aria-expanded={active===row.label} onFocus={()=>setActive(row.label)} onBlur={close} onPointerEnter={event=>{if(event.pointerType==='mouse')setActive(row.label);}} onClick={()=>{const next=clicked.current===row.label?'':row.label;clicked.current=next;setActive(next);}} style={{'--bar-width':`${(row.value??0)/max*100}%`} as CSSProperties}><span className="prompt-bar-fill"/></button><strong>{percent?pct(row.value):row.value??'—'}</strong></div>)}<div className="prompt-axis"><span>0{percent?'%':''}</span><span>{percent?'100%':max}</span></div>{tooltip&&<p ref={tip} role="tooltip" className="prompt-tooltip prompt-chart-tooltip">{tooltip}</p>}</div>;
}
function ElementHeat({employees}:{employees:PromptReport['employees']}){
  const [active,setActive]=useState(''),clicked=useRef(''),{root,tip}=usePromptTooltip(active);
  const close=()=>{clicked.current='';setActive('');},elements=Object.entries(promptElementLabels) as [keyof typeof promptElementLabels,string][];
  const cells=employees.flatMap(row=>elements.map(([key,label])=>({id:row.employeeId+':'+key,detail:`${row.employee} · ${label} · ${count(row.elements[key])}`}))),tooltip=cells.find(cell=>cell.id===active)?.detail;
  return <div ref={root} className="prompt-heat-chart" onPointerLeave={event=>{if(event.pointerType==='mouse')close();}} onKeyDown={event=>{if(event.key==='Escape')close();}}><div className="prompt-table-wrap"><table className="prompt-heat"><thead><tr><th>员工</th>{elements.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{employees.map(row=><tr key={row.employeeId}><th>{row.employee}</th>{elements.map(([key,label])=>{const value=row.elements[key],id=row.employeeId+':'+key,detail=`${row.employee} · ${label} · ${count(value)}`;return <td key={key}><button style={{'--heat':value.value??0} as CSSProperties} aria-label={`${detail} · ${pct(value.value)}`} aria-expanded={active===id} onFocus={()=>setActive(id)} onBlur={close} onPointerEnter={event=>{if(event.pointerType==='mouse')setActive(id);}} onClick={()=>{const next=clicked.current===id?'':id;clicked.current=next;setActive(next);}}>{pct(value.value)}</button></td>;})}</tr>)}</tbody></table></div>{tooltip&&<p ref={tip} role="tooltip" className="prompt-tooltip prompt-chart-tooltip">{tooltip}</p>}</div>;
}
function Citation({cites}:{cites:InsightCitation[]}){return <span className="prompt-citations">{cites.map((cite,index)=><a key={index} href={cite.webPath}>原句 {index+1}</a>)}</span>;}
function Examples({items,positive}:{items:PromptExample[];positive:boolean}){return <div className="prompt-example-column"><h3>{positive?'后续未返工的写法':'后续发生返工的写法'}</h3>{!items.length?<p className="prompt-empty">暂无匹配示例</p>:items.map(item=><article className="prompt-example" data-positive={positive} key={item.messageId}><blockquote>{item.citations.map(cite=>cite.quote).join('\n')}</blockquote><p>{item.elements.map(key=>promptElementLabels[key]).join(' · ')}</p><div><strong>{item.employee}</strong><span className="prompt-inference">{item.correctionIds?.length?'含人工更正':'模型推断'}</span><Citation cites={item.citations}/></div><details><summary>后续提示词与分析版本</summary>{item.followingCitations.map((cite,index)=><p key={index}><a href={cite.webPath}>{cite.quote}</a></p>)}<p className="prompt-version">{item.analysisVersions.join(' · ')}</p></details></article>)}</div>;}
export function PromptReportPage({request}:{request:Request}){
  const [query,setQuery]=useState<PromptReportQuery>(hashQuery),[page,setPage]=useState<PromptReport>(),[people,setPeople]=useState<PromptReport['employees']>([]),[projects,setProjects]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0),[taskTooltip,setTaskTooltip]=useState('');
  useEffect(()=>{const change=()=>{if(location.hash.split('?')[0]==='#prompts')setQuery(hashQuery());};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
  useEffect(()=>{const abort=new AbortController();setBusy(true);setError('');setPage(undefined);request('/api/prompt-report?'+params(query),abort.signal).then(response=>response.json()).then((report:PromptReport)=>{if(abort.signal.aborted)return;setPage(report);setPeople(previous=>[...new Map([...previous,...report.employees].map(row=>[row.employeeId,row])).values()].sort((a,b)=>a.employee.localeCompare(b.employee,'zh-CN')));setProjects(previous=>[...new Set([...previous,...report.projects])].sort());}).catch(error=>{if(!abort.signal.aborted)setError(error.message);}).finally(()=>{if(!abort.signal.aborted)setBusy(false);});return()=>abort.abort();},[query,retry]);
  function select(next:Partial<PromptReportQuery>){const value={...query,...next,version:undefined,usageVersion:undefined,week:undefined};const target='#prompts?'+params(value);if(location.hash===target)setRetry(value=>value+1);else location.hash=target;}
  async function recompute(){setBusy(true);setError('');try{const data:PromptReport=await(await request('/api/prompt-report/recompute',undefined,'POST',{...query,version:undefined,usageVersion:undefined})).json();setQuery({...query,version:data.version});}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  async function download(){if(!page)return;try{const response=await request('/api/prompt-report/export?'+params({...query,version:page.version})),url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=`skynet-prompts-${page.version}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){setError((error as Error).message);}}
  const elements=Object.entries(promptElementLabels) as [keyof typeof promptElementLabels,string][];
  return <section className="usage-metrics prompt-report workspace-page" aria-label="提示词分析" aria-busy={busy} onKeyDown={event=>{if(event.key==='Escape'){setTaskTooltip('');}}}>
    <div className="usage-page-head"><h1>提示词分析</h1><div className="usage-export-actions">{!query.week&&<button disabled={busy||!page} onClick={recompute}>从原件重算</button>}<button disabled={busy||!page} onClick={download}>导出当前版本</button></div></div>
    <div className="usage-filters"><div className="usage-filter-row"><div className="usage-periods" role="group" aria-label="时间范围">{([['this-week','本周'],['last-week','上周'],['since-enrollment','接入至今']] as const).map(([period,label])=><button key={period} aria-pressed={!query.week&&query.period===period} onClick={()=>select({period})}>{label}</button>)}</div>
      <label>员工<select value={query.employeeId??''} onChange={event=>select({employeeId:event.target.value||undefined})}><option value="">全部员工</option>{people.map(person=><option key={person.employeeId} value={person.employeeId}>{person.employee}</option>)}</select></label>
      <label>Agent<select value={query.source??''} onChange={event=>select({source:event.target.value as PromptReportQuery['source']||undefined})}><option value="">全部 Agent</option>{(['codex-cli','codex-desktop','claude-code-cli'] as const).map(source=><option key={source} value={source}>{sourceLabel(source)}</option>)}</select></label>
      <label>项目<select value={query.project===undefined?'all':'project:'+query.project} onChange={event=>select({project:event.target.value==='all'?undefined:event.target.value.slice(8)})}><option value="all">全部项目</option>{projects.map(project=><option key={project} value={'project:'+project}>{project||'未归类项目'}</option>)}</select></label></div>
      {page&&<p className="prompt-scope">{page.scope.from} — {page.scope.to} · 北京时间 · 数据截至 {new Date(page.dataAsOf).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}</p>}
    </div>
    <div className="workspace-scroll prompt-scroll">{busy&&<p role="status">正在读取提示词分析…</p>}{error&&<div role="alert"><p>{error}</p><button onClick={()=>setRetry(value=>value+1)}>重试</button></div>}
      {page&&!page.kpis.prompts&&<p className="usage-empty">暂无提示词</p>}
      {page&&page.kpis.prompts>0&&<><div className="prompt-kpis"><div><span>提示词</span><strong>{page.kpis.prompts}</strong><small>{page.kpis.sessions} 个会话 · 中位长度 {page.kpis.medianLength.value??'—'} 字</small></div>{([['提供了上下文',page.kpis.context],['返工率',page.kpis.rework],['无返工会话',page.kpis.cleanSessions],['Agent 追问',page.kpis.clarification]] as const).map(([label,value])=><div key={label}><span>{label}</span><strong>{pct(value.value)}</strong><small>{count(value)}</small></div>)}</div>
      <div className="prompt-grid"><Figure label="提示词要素覆盖" title="提示词要素覆盖" table={<table><thead><tr><th>员工</th>{elements.map(([key,label])=><th key={key}>{label}</th>)}<th>提示词</th></tr></thead><tbody>{page.employees.map(row=><tr key={row.employeeId}><th>{row.employee}</th>{elements.map(([key])=><td key={key}>{pct(row.elements[key].value)}<small>{count(row.elements[key])}</small></td>)}<td>{row.prompts}</td></tr>)}</tbody></table>}>
        <ElementHeat employees={page.employees}/>
      </Figure><Figure label="上下文与返工" title="上下文与返工" note={<><span>相关不等于因果</span>{page.contextComparison.unknownPairs>0&&` · ${page.contextComparison.unknownPairs} 对上下文未知`}</>} table={<table><thead><tr><th>上一条提示词</th><th>后续返工率</th><th>返工 / 有效后续</th><th>未知</th></tr></thead><tbody>{([['提供了上下文',page.contextComparison.withContext],['没有上下文',page.contextComparison.withoutContext]] as const).map(([label,value])=><tr key={label}><th>{label}</th><td>{pct(value.value)}</td><td>{value.numerator} / {value.denominator}</td><td>{value.unknown}</td></tr>)}</tbody></table>}><Bars percent rows={[{label:'上一条有上下文',value:page.contextComparison.withContext.value,detail:count(page.contextComparison.withContext)},{label:'上一条无上下文',value:page.contextComparison.withoutContext.value,detail:count(page.contextComparison.withoutContext)}]}/></Figure></div>
      <div className="prompt-bottom-grid"><div className="prompt-length-pair"><Figure label="长度数量" title="按长度分段的数量" table={<table><thead><tr><th>长度</th><th>提示词数量</th></tr></thead><tbody>{page.lengths.map(row=><tr key={row.label}><th>{row.label}</th><td>{row.count}</td></tr>)}</tbody></table>}><Bars rows={page.lengths.map(row=>({label:row.label,value:row.count,detail:`${row.label} · ${row.count} 条提示词`}))}/></Figure>
      <Figure label="长度返工率" title="按长度分段的返工率" table={<table><thead><tr><th>长度</th><th>返工率</th><th>返工 / 非首条</th><th>未知</th></tr></thead><tbody>{page.lengths.map(row=><tr key={row.label}><th>{row.label}</th><td>{pct(row.rework.value)}</td><td>{row.rework.numerator} / {row.rework.denominator}</td><td>{row.rework.unknown}</td></tr>)}</tbody></table>}><Bars percent rows={page.lengths.map(row=>({label:row.label,value:row.rework.value,detail:`${row.label} · ${count(row.rework)}`}))}/></Figure></div>
      <Figure label="任务类型构成" title="提示词的任务类型构成" table={<table><thead><tr><th>员工</th>{groups.map(group=><th key={group.label}>{group.label}</th>)}<th>合计</th></tr></thead><tbody>{page.employees.map(row=><tr key={row.employeeId}><th>{row.employee}</th>{groups.map(group=><td key={group.label}>{row.taskMix.filter(task=>group.types.includes(task.taskType)).reduce((sum,task)=>sum+task.prompts,0)}</td>)}<td>{row.prompts}</td></tr>)}</tbody></table>}>
        <div className="prompt-task-bars">{page.employees.map(row=>{const slices=groups.map((group,index)=>({label:group.label,series:index+1,count:row.taskMix.filter(task=>group.types.includes(task.taskType)).reduce((sum,task)=>sum+task.prompts,0)})),detail=slices.filter(slice=>slice.count>0).map(slice=>`${row.employee} · ${slice.label} · ${slice.count} / ${row.prompts} 条`).join('；');return <div key={row.employeeId}><strong>{row.employee}</strong><div className="prompt-stack" aria-hidden="true">{slices.map(slice=>slice.count>0&&<span key={slice.label} data-series={slice.series} style={{width:`${slice.count/row.prompts*100}%`}}/>)}</div><button className="prompt-task-detail" aria-label={detail} onFocus={()=>setTaskTooltip(detail)} onBlur={()=>setTaskTooltip('')} onMouseEnter={()=>setTaskTooltip(detail)} onMouseLeave={()=>setTaskTooltip('')} onClick={()=>setTaskTooltip(detail)}>{row.prompts} 条</button></div>;})}</div><div className="prompt-legend">{groups.map((group,index)=><span key={group.label} data-series={index+1}>{group.label}</span>)}</div>
      {taskTooltip&&<p role="tooltip" className="prompt-tooltip">{taskTooltip}</p>}</Figure></div>
      <section className="usage-figure prompt-examples"><h2>写法示例</h2><div className="prompt-grid"><Examples items={page.examples.positive} positive/><Examples items={page.examples.negative} positive={false}/></div></section>
      <section className="usage-figure prompt-suggestions"><h2>写法建议 <span className="prompt-inference">模型推断</span></h2>{page.employees.map(person=>{const suggestion=page.suggestions.find(item=>item.employeeId===person.employeeId);return <div key={person.employeeId}><strong>{person.employee}</strong><span>{suggestion?.text??'暂无可用分析建议'}</span>{suggestion&&<Citation cites={suggestion.citations}/>}</div>;})}</section>
      </>}
      {page&&<details className="prompt-definitions"><summary>指标口径与版本</summary><p>数量与长度：原始员工、来源日期及项目下的真实用户消息；Unicode 字符计数，多文本块合并为一条。恢复和续聊按原事件去重。长度未知 {page.kpis.medianLength.unknownCount} 条。</p><p>模型指标保留有效样本分母和未知数。返工排除首条；无返工只在所选范围的逻辑会话推断完整时统计。追问次数除以回复推断完整的提示词数，没有回复或回复推断未知的提示词单列。</p><p>上下文对比取上一条提示词的上下文与当前后续提示词的返工；前条可以来自范围外，仅作关联。示例按四要素覆盖及下一条返工筛选，最多各三条；建议来自当前固定分析结果。</p><p>比例、任务类型与写法示例来自模型推断及人工更正，固定版本保留来源。{page.unknownReasons.join('；')}</p><p className="prompt-version">版本 {page.version} · 来源 {page.usageVersion} · {page.algorithmVersion}</p></details>}
    </div>
  </section>;
}
