import { useEffect, useState } from 'react';
import { sourceLabel, type SessionSummary } from '../../packages/contracts/archive.js';
import type { Detail } from './SessionDetail.js';
import './recovery-flow.css';

type Props={sessions:SessionSummary[];hasMore:boolean;onLoadMore:()=>void;request:(path:string,signal?:AbortSignal)=>Promise<Response>};
const dayOf=(value:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
const timeOf=(value:string)=>new Date(value).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hour12:false});
export function RecoveryFlow({sessions,hasMore,onLoadMore,request}:Props){
  const initial=new URLSearchParams(location.hash.split('?')[1]).get('snapshot')??'';
  const [step,setStep]=useState(initial?2:1),[selected,setSelected]=useState(initial),[employee,setEmployee]=useState(''),[date,setDate]=useState('');
  const [method,setMethod]=useState<'readable'|'recovery'>('readable'),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[downloaded,setDownloaded]=useState(false);
  const employees=[...new Map(sessions.map(s=>[s.employeeId,{id:s.employeeId,name:s.employee}])).values()].sort((a,b)=>a.name.localeCompare(b.name,'zh-CN'));
  const who=employee||employees[0]?.id||'';const byEmployee=sessions.filter(s=>s.employeeId===who);const dates=[...new Set(byEmployee.map(s=>dayOf(s.committed_at)))].sort().reverse();
  const chosenDate=date||dates[0]||dayOf(new Date().toISOString());
  const month=chosenDate.slice(0,7),[year,monthNumber]=month.split('-').map(Number);const days=new Date(year!,monthNumber!,0).getDate(),pad=(new Date(year!,monthNumber!-1,1).getDay()+6)%7;
  const list=byEmployee.filter(s=>dayOf(s.committed_at)===chosenDate);
  useEffect(()=>{if(!selected){setDetail(null);return;}const abort=new AbortController();setError('');setDetail(null);request('/api/snapshots/'+selected+'?summary=true',abort.signal).then(r=>r.json()).then(v=>{if(!abort.signal.aborted)setDetail(v);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[selected]);
  async function download(kind:'raw'|'readable'|'recovery'){
    if(!detail)return;setBusy(true);setError('');setDownloaded(false);
    try{const response=await request(`/api/snapshots/${detail.snapshotId}/${kind}`);const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=detail.snapshotId+({raw:'.jsonl',readable:'.txt',recovery:'.skynet-recovery.json'}[kind]);a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setDownloaded(true);}
    catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  return <section className="recovery-flow workspace-page" aria-label="会话找回"><div className="recovery-page-head"><h1>会话找回</h1></div>
    <ol className="restore-steps" aria-label="找回步骤">{['选择会话','选择格式','下载'].map((label,index)=><li key={label} aria-current={step===index+1?'step':undefined} className={step>index+1?'is-done':''}>{step>index+1?<button onClick={()=>setStep(index+1)}><span>✓</span>{label}</button>:<span><b>{index+1}</b>{label}</span>}</li>)}</ol>
    <div className="workspace-scroll" data-scroll-region="recovery">{step===1?<><div className="restore-book"><section className="restore-people" aria-label="员工"><h2>找回谁的会话</h2><div role="group" aria-label="选择员工">{employees.map(person=><button key={person.id} aria-pressed={person.id===who} onClick={()=>{setEmployee(person.id);setSelected('');setDate('');}}><span className="session-avatar" aria-hidden="true">{Array.from(person.name)[0]}</span>{person.name}{employees.filter(other=>other.name===person.name).length>1&&<small> · {person.id.slice(0,8)}</small>}</button>)}</div><dl><div><dt>已加载存档</dt><dd>{byEmployee.length} 个</dd></div></dl>{hasMore&&<button onClick={onLoadMore}>加载更多会话</button>}</section>
      <section className="restore-calendar" aria-label="选择日期"><div><h2>{year}年{monthNumber}月</h2><span>北京时间</span></div><label className="restore-date-input">提交日期<input type="date" value={chosenDate} onChange={event=>{setDate(event.target.value);setSelected('');}}/></label><div className="restore-calendar-grid">{['一','二','三','四','五','六','日'].map(d=><span key={d} className="restore-weekday">{d}</span>)}{Array.from({length:pad},(_,i)=><span key={'pad'+i}/>)}{Array.from({length:days},(_,i)=>{const day=`${month}-${String(i+1).padStart(2,'0')}`;return dates.includes(day)?<button key={day} aria-label={`${day}，有存档会话`} aria-pressed={chosenDate===day} onClick={()=>{setDate(day);setSelected('');}}>{i+1}</button>:<span key={day} className="restore-no-record">{i+1}</span>;})}</div><p><i/>有存档会话</p></section>
      <section className="restore-slots" aria-label="选择会话"><h2>{chosenDate}</h2>{list.length?list.map(session=><div key={session.id} className={selected===session.id?'is-selected':''}><button className="restore-slot" aria-pressed={selected===session.id} onClick={()=>setSelected(session.id)}><time>{timeOf(session.committed_at)}</time><strong>{session.project.replaceAll('\\','/').split('/').filter(Boolean).at(-1)||'未归类项目'}</strong><span>{sourceLabel(session.source)} · {session.byte_length.toLocaleString('zh-CN')} 字节</span></button>{selected===session.id&&<button className="primary" onClick={()=>setStep(2)}>下一步 →</button>}</div>):<p>当天暂无会话</p>}</section></div>{sessions.length===0&&<div className="empty"><h2>暂无会话</h2></div>}</>
    :!detail?<p role="status">{error?'无法读取所选会话。':'正在读取所选原件…'}</p>:<><div className="restore-summary"><span className="session-avatar" aria-hidden="true">{Array.from(detail.employee)[0]}</span><div><strong>{detail.manifest.project||'未归类项目'}</strong><p>{detail.employee} · {sourceLabel(detail.manifest.source)} · {detail.manifest.sourceOs} · {dayOf(detail.committedAt)}</p></div><span className="badge">原件已提交</span></div>
      {step===2?<><div className="restore-methods" role="radiogroup" aria-label="找回方式"><label className={method==='readable'?'is-selected':''}><input type="radio" name="restore-method" checked={method==='readable'} onChange={()=>setMethod('readable')}/><strong>完整可读导出</strong><span className="restore-format">TXT</span></label><label className={method==='recovery'?'is-selected':''}><input type="radio" name="restore-method" checked={method==='recovery'} onChange={()=>setMethod('recovery')}/><strong>恢复资料包</strong><span className="restore-format">JSON · 原件与关联材料</span></label></div>
        <section className="restore-snapshot"><h2>所选会话</h2><dl><div><dt>来源版本</dt><dd>{detail.manifest.sourceVersion}</dd></div><div><dt>提交时间</dt><dd>{new Date(detail.committedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}</dd></div><div><dt>SHA-256</dt><dd className="hash">{detail.manifest.hash}</dd></div></dl><a href={'#'+selected}>阅读会话</a></section><div className="restore-footer"><button onClick={()=>setStep(1)}>← 返回</button><button className="primary" onClick={()=>setStep(3)}>下一步 →</button></div></>
      :<><ul className="restore-checks"><li><strong>材料范围</strong><span>{detail.manifest.byteLength.toLocaleString('zh-CN')} 字节原件，{detail.manifest.capture?.materials.length??0} 项关联材料</span></li><li><strong>来源版本</strong><span>{sourceLabel(detail.manifest.source)} · {detail.manifest.sourceVersion} · {detail.manifest.sourceOs}</span></li></ul><div className="restore-download"><h2>{method==='readable'?'完整可读导出':'准备恢复资料'}</h2><div className="export-actions"><button className="primary" disabled={busy} onClick={()=>download(method)}>{busy?'正在准备…':method==='readable'?'下载完整可读材料':'下载恢复资料包'}</button><button disabled={busy} onClick={()=>download('raw')}>下载原件 JSONL</button></div>{downloaded&&<p role="status">下载已准备</p>}</div><div className="restore-footer"><button onClick={()=>setStep(2)}>← 返回选择方式</button><a href={'#'+selected}>查看会话</a></div></>}
    </>}{error&&<p className="error" role="alert">{error}</p>}
  </div></section>;
}
