import {useEffect,useState,type CSSProperties} from 'react';
import type {TeamReport,TeamReportQuery} from '../../packages/contracts/team-report.js';
import type {OutputAmount} from '../../packages/contracts/usage-output.js';
import {sourceLabel} from '../../packages/contracts/archive.js';
import {monday,addDays} from '../../packages/contracts/work-views.js';
import './team-usage.css';
import {profileEntry} from './profile-navigation.js';

type Request=(path:string,signal?:AbortSignal)=>Promise<Response>;
export const teamParams=(query:object)=>new URLSearchParams(Object.entries(query).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)]));
export function teamHashQuery():TeamReportQuery {const p=new URLSearchParams(location.hash.split('?')[1]);return {period:(p.get('period')??'this-week') as TeamReportQuery['period'],...(p.has('coverageOffset')?{coverageOffset:Number(p.get('coverageOffset'))}:{}),...Object.fromEntries(['employeeId','source','project','week','version'].flatMap(key=>p.has(key)?[[key,p.get(key)!]]:[]))};}
const number=(value:number)=>value.toLocaleString('zh-CN');
const compact=(value:number)=>value>=1e6?`${Number((value/1e6).toFixed(2))}M`:value>=1000?`${Number((value/1000).toFixed(1))}k`:number(value);
const percent=(value:number|null)=>value===null?'未知':`${Number((value*100).toFixed(1))}%`;
const duration=(value:number|null)=>value===null?'未知':value<60000?`${Number((value/1000).toFixed(1))} 秒`:`${Number((value/60000).toFixed(1))} 分`;
const coverageLabel={'gap-observed':'采集缺口','observations-only':'已有采集观测',unknown:'覆盖未知'};
function Amount({value}:{value:OutputAmount}){return <><b>{value.value===null&&!value.known?'未知':number(value.known)}</b>{value.unknownSessions>0&&<small>{value.known?'已知部分 + ':''}{value.unknownSessions} 个会话未知</small>}</>;}
function Spark({values,label}:{values:{date:string;value:number|null}[];label:string}){const [open,setOpen]=useState(false),max=Math.max(1,...values.map(day=>day.value??0));const paths:string[][]=[];let part:string[]=[];values.forEach((day,index)=>{if(day.value===null){if(part.length)paths.push(part);part=[];}else part.push(`${2+index/Math.max(1,values.length-1)*176},${35-day.value/max*30}`);});if(part.length)paths.push(part);return <div className="team-spark" onKeyDown={event=>{if(event.key==='Escape')setOpen(false);}}><svg viewBox="0 0 180 40" aria-hidden="true">{paths.map((points,index)=><polyline key={index} points={points.join(' ')}/>)}{values.map((day,index)=>day.value!==null&&<circle key={day.date} cx={2+index/Math.max(1,values.length-1)*176} cy={35-day.value/max*30} r="2"/>)}</svg><button aria-label={label+'详情'} onFocus={()=>setOpen(true)} onBlur={()=>setOpen(false)} onClick={()=>setOpen(!open)} onMouseEnter={()=>setOpen(true)} onMouseLeave={()=>setOpen(false)}>详情</button>{open&&<div role="tooltip" className="team-trend-tooltip">{values.map(day=><span key={day.date}>{day.date}：{day.value??'未知'}</span>)}</div>}</div>;}
export function TeamKpis({report,weekly=false}:{report:TeamReport;weekly?:boolean}){const [table,setTable]=useState(false);return <section className="team-usage-summary" aria-label={weekly?'使用画像':'期间使用概况'}><div className="team-section-heading"><h2>{weekly?'使用画像':'使用概况'}</h2><div className="team-chart-toggle"><button aria-label="每日趋势切换为图表" aria-pressed={!table} onClick={()=>setTable(false)}>图表</button><button aria-label="每日趋势切换为表格" aria-pressed={table} onClick={()=>setTable(true)}>表格</button></div></div><div className={'team-usage-kpis'+(weekly?' is-weekly':'')}>
      {!weekly&&<article aria-label="活跃员工"><span>活跃员工</span><strong>{report.activeEmployees.active}<small> / {report.activeEmployees.total}</small></strong><p>{report.totals.sessions} 个会话</p></article>}
      <article><span>Token 输入</span><strong>{report.totals.inputTokens===null&&!report.totals.knownInputTokens?'未知':compact(report.totals.knownInputTokens)}</strong><p>{report.totals.unknownInputSessions>0?`已知部分 + ${report.totals.unknownInputSessions} 个会话未知`:`${report.totals.sessions} 个会话`}</p>{!table&&<Spark label="每日 Token 输入" values={report.daily.map(day=>({date:day.date,value:day.inputTokens}))}/>}</article>
      <article><span>已验证结果 <em>模型推断</em></span><strong><Amount value={report.outputs.verified}/></strong><p>仅声称 {report.outputs.claimed.value??'未知'}</p>{!table&&<Spark label="每日已验证结果" values={report.daily.map(day=>({date:day.date,value:day.outputs.verified.value}))}/>}</article>
      {weekly?<article><span>提示词与返工 <em>模型推断</em></span><strong>{report.prompts.prompts}</strong><p>返工 {percent(report.prompts.rework.value)} · {report.prompts.rework.numerator} / {report.prompts.rework.denominator}{report.prompts.rework.unknown>0&&` · ${report.prompts.rework.unknown} 未知`}</p></article>:<article><span>代码变更</span><strong><Amount value={report.outputs.codeChanges}/></strong><p>+{report.outputs.codeChanges.added} / −{report.outputs.codeChanges.removed} 行</p>{!table&&<Spark label="每日代码变更" values={report.daily.map(day=>({date:day.date,value:day.outputs.codeChanges.value}))}/>}</article>}
      <article><span>等待中位数</span><strong>{duration(report.waits.medianMs)}</strong><p>{report.waits.knownCount} 个完整间隔{report.waits.unknownCount>0&&` · ${report.waits.unknownCount} 未知`}</p><small>权限等待：未知</small></article>
    </div>{table&&<div className="team-table-wrap"><table><thead><tr><th>日期</th><th>Token 输入</th><th>未知 Token 会话</th><th>已验证结果</th><th>代码变更</th></tr></thead><tbody>{report.daily.map(day=><tr key={day.date}><th>{day.date}</th><td>{day.inputTokens??'未知'}</td><td>{day.excludedSessions}</td><td><Amount value={day.outputs.verified}/></td><td><Amount value={day.outputs.codeChanges}/></td></tr>)}</tbody></table></div>}
    {weekly&&<nav className="team-profile-links" aria-label="使用报表"><a href={report.links.usage.web}>用量与产出</a><a href={report.links.prompts.web}>提示词分析</a><a href={report.links.waits.web}>响应与等待</a></nav>}
  </section>;}
export function TeamPeople({report,query}:{report:TeamReport;query:TeamReportQuery}){const origin='#coverage?'+teamParams({...query,version:report.version});const maximum=(kind:'tokens'|'verified'|'code')=>Math.max(1,...report.people.map(person=>kind==='tokens'?person.totals.knownInputTokens:person.outputs[kind==='verified'?'verified':'codeChanges'].known));const bar=(value:number,kind:'tokens'|'verified'|'code')=><span aria-hidden="true" className="team-cell-bar" style={{'--amount':`${value/maximum(kind)*100}%`} as CSSProperties}/>;return <section className="team-people" aria-label="期间人员汇总"><div className="team-section-heading"><h2>人员汇总</h2><a href={report.links.usage.web}>完整报表 →</a></div><div className="team-table-wrap"><table><thead><tr><th>员工</th><th>使用能力<small>接入至今 · 默认</small></th><th>会话</th><th>Token 输入</th><th>已验证结果</th><th>代码变更</th><th>提示词 · 返工率</th><th>等待中位数</th><th>覆盖</th></tr></thead><tbody>{report.people.map(person=><tr key={person.employeeId}><th><a aria-label={person.employee+' 周工作'} href={'#work?'+teamParams({kind:'weekly',subject:person.employeeId,from:monday(report.scope.from),to:addDays(monday(report.scope.from),6),source:query.source,project:query.project})}>{person.employee}</a></th><td className="team-capability">{person.capability?<><a aria-label={person.employee+' 使用能力画像'} {...profileEntry(person.capability.profilePath,origin)}><span data-level={person.capability.level}>{person.capability.level}</span><b>{person.capability.index===null?'—':Math.round(person.capability.index)}</b><span aria-hidden="true">↗</span></a><small>可信度{person.capability.confidence}</small><small>{person.capability.reason}</small>{person.capability.coverageIssues.length>0&&<small className="team-capability-coverage">{person.capability.coverageIssues.join('；')}</small>}</>:<span>—</span>}</td><td>{person.totals.sessions}</td><td><b>{person.totals.inputTokens===null&&!person.totals.knownInputTokens?'未知':compact(person.totals.knownInputTokens)}</b>{bar(person.totals.knownInputTokens,'tokens')}{person.totals.unknownInputSessions>0&&<small>已知部分 + {person.totals.unknownInputSessions} 个会话未知</small>}</td><td><Amount value={person.outputs.verified}/>{bar(person.outputs.verified.known,'verified')}<small>模型推断</small></td><td><Amount value={person.outputs.codeChanges}/>{bar(person.outputs.codeChanges.known,'code')}<small>+{person.outputs.codeChanges.added} / −{person.outputs.codeChanges.removed}</small></td><td>{person.prompts.prompts} · {percent(person.prompts.rework.value)}<small>{person.prompts.rework.numerator} / {person.prompts.rework.denominator}{person.prompts.rework.unknown>0&&` · ${person.prompts.rework.unknown} 未知`} · 模型推断</small></td><td>{duration(person.waits.medianMs)}<small>{person.waits.knownCount} 个间隔{person.waits.unknownCount>0&&` · ${person.waits.unknownCount} 未知`}</small></td><td><span data-coverage={person.coverage}>{coverageLabel[person.coverage]}</span></td></tr>)}</tbody></table></div></section>;}
export function TeamFilters({query,report,onChange}:{query:TeamReportQuery;report?:TeamReport;onChange:(query:TeamReportQuery)=>void}){const [people,setPeople]=useState<TeamReport['people']>([]),[projects,setProjects]=useState<string[]>([]);useEffect(()=>{if(report){setPeople(previous=>[...new Map([...previous,...report.people].map(row=>[row.employeeId,row])).values()].sort((a,b)=>a.employee.localeCompare(b.employee,'zh-CN')));setProjects(previous=>[...new Set([...previous,...report.projects,...(query.project===undefined?[]:[query.project])])].sort());}},[report?.version]);const select=(next:Partial<TeamReportQuery>)=>onChange({...query,...next,version:undefined,week:undefined,coverageOffset:undefined});return <div className="team-filters"><div className="team-periods" role="group" aria-label="时间范围">{([['this-week','本周'],['last-week','上周'],['since-enrollment','接入至今']] as const).map(([period,label])=><button key={period} aria-pressed={!query.week&&query.period===period} onClick={()=>select({period})}>{label}</button>)}</div><label>员工<select value={query.employeeId??''} onChange={event=>select({employeeId:event.target.value||undefined})}><option value="">全部员工</option>{people.map(person=><option key={person.employeeId} value={person.employeeId}>{person.employee}</option>)}</select></label><label>Agent<select value={query.source??''} onChange={event=>select({source:event.target.value as TeamReportQuery['source']||undefined})}><option value="">全部 Agent</option>{(['codex-cli','codex-desktop','claude-code-cli'] as const).map(source=><option key={source} value={source}>{sourceLabel(source)}</option>)}</select></label><label>项目<select value={query.project===undefined?'all':'project:'+query.project} onChange={event=>select({project:event.target.value==='all'?undefined:event.target.value.slice(8)})}><option value="all">全部项目</option>{projects.map(project=><option key={project} value={'project:'+project}>{project||'未归类项目'}</option>)}</select></label></div>;}
export function WeeklyUsage({request,employeeId,week,refresh=0}:{request:Request;employeeId:string;week:string;refresh?:number}){const [report,setReport]=useState<TeamReport>(),[error,setError]=useState('');const q=new URLSearchParams(location.hash.split('?')[1]),source=q.get('source')??undefined,project=q.has('project')?q.get('project')!:undefined;useEffect(()=>{const abort=new AbortController();setReport(undefined);setError('');request('/api/team-report/weekly?'+teamParams({employeeId,week,source,project}),abort.signal).then(response=>response.json()).then(value=>{if(!abort.signal.aborted)setReport(value);}).catch(error=>{if(!abort.signal.aborted)setError(error.message);});return()=>abort.abort();},[employeeId,week,source,project,refresh]);return error?<p role="alert">{error}</p>:report?<><TeamKpis weekly report={report}/><p className="team-cutoff">{report.scope.from} — {report.scope.to} · 截至 {new Date(report.dataAsOf).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</p></>:<p role="status">读取使用画像…</p>;}
